require('config.treesitter')
require('config.telescope')
require('config.bufferline')
require('config.lualine')
require('config.web_devicons')
require('config.debugger')
require('config.ts_rainbow')
require('config.whichkey')
require('config.nvim-autopairs')
require('config.gitsigns')
require('config.neotest')
require('config.toggleterm')
require('config.hlslens')
require('config.comment')
require('config.trouble')
require('config.neoclip')
require('config.sort')
require('config.nvim-tree')
require('config.symbols-outline')
require('config.leap')
require('config.oil')
require('config.diffview')
require('config.bqf')

-- LSP
require('config.lsp')

require('marks').setup()
require('rest-nvim').setup({})
