theme = "molokai"

[editor]
line-number = "relative"
mouse = true
scrolloff = 7
bufferline = "always"
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"C-h" = "move_char_left"
"C-j" = "move_line_down"
"C-k" = "move_line_up"
"C-l" = "move_char_right"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
