-- Convert invit.vim to init.lua : https://www.khuedoan.com/posts/convert-from-init-vim-to-init-lua/    
require('utils')
require('plugins')
require('settings')
require('nv-colorscheme')
require('keymappings')
require('nv-treesitter')
require('nv-telescope')
require('nv-bufferline')
require('nv-lualine')
require('nv-web_devicons')
require('nv-nvim_tree')
require('nv-nvimdap')
require('nv-ts_rainbow')
require('nv-whichkey')
require('nv-nvim-remote-containers')
require('nv-nvim-autopairs')
require('nv-ncm2')
require('nv-neogit')
-- LSP
require('nv-lsp')
