-- Convert invit.vim to init.lua : https://www.khuedoan.com/posts/convert-from-init-vim-to-init-lua/    
require('utils')
require('plugins')
require('settings')
require('config.colorscheme')
require('keymappings')
require('config.treesitter')
require('config.telescope')
require('config.bufferline')
require('config.lualine')
require('config.web_devicons')
require('config.nvim-tree')
require('config.debugger')
require('config.ts_rainbow')
require('config.whichkey')
require('config.nvim-remote-containers')
require('config.nvim-autopairs')
require('config.gitsigns')
require('config.neotest')
require('config.toggleterm')
require('config.harpoon')
require('config.hlslens')
require('config.comment')

-- LSP
require('config.lsp')
